{** template-description:default **}

{include file="addons/my_changes/blocks/list_templates/asim_custom.tpl"
show_name=true
show_old_price=true
show_price=true
show_rating=true
show_clean_price=true
show_list_discount=true
show_add_to_cart=$show_add_to_cart|default:true
but_role="action"
show_features=true
show_list_buttons=true 
show_product_labels=true
show_discount_label=true
show_shipping_label=true
show_name=true 
show_sku=false 
show_rating=true 
show_features=true 
show_prod_descr=true 
show_old_price=true 
show_price=true 
show_clean_price=true 
show_list_discount=true 
show_product_labels=true
product_labels_mini=true
show_discount_label=true
show_shipping_label=true
show_product_amount=true 
show_product_edp=true 
show_add_to_cart=true 
show_list_buttons=true 
show_descr=true 
but_role="action"}